// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./components/color-avatar/components/background.tsx')['default']
    ColorAvatar: typeof import('./components/color-avatar/index.tsx')['default']
    Logo: typeof import('./components/logo.tsx')['default']
    Navbar: typeof import('./components/action-bar.tsx')['default']
    Scrollbar: typeof import('./components/scrollbar.tsx')['default']
    SectionWrapper: typeof import('./components/section-wrapper.tsx')['default']
  }
}
